export const CARD_PORTRAIT_SOURCES = {
  mbappe: "/cards/players/mbappe.jpg",
  dembele: "/cards/players/dembele.jpg",
  saliba: "/cards/players/saliba.jpg",
  maignan: "/cards/players/maignan.jpg",
  rodri: "/cards/players/rodri.jpg",
  pedri: "/cards/players/pedri.jpg",
  lamine_yamal: "/cards/players/lamine_yamal.jpg",
  carvajal: "/cards/players/carvajal.jpg",
  messi: "/cards/players/messi.jpg",
  lautaro: "/cards/players/lautaro.jpg",
  mac_allister: "/cards/players/mac_allister.jpg",
  emiliano_martinez: "/cards/players/emiliano_martinez.jpg",
  bellingham: "/cards/players/bellingham.jpg",
  kane: "/cards/players/kane.jpg",
  saka: "/cards/players/saka.jpg",
  stones: "/cards/players/stones.jpg",
  bruno_fernandes: "/cards/players/bruno_fernandes.jpg",
  vitinha: "/cards/players/vitinha.jpg",
  rafael_leao: "/cards/players/rafael_leao.jpg",
  ruben_dias: "/cards/players/ruben_dias.jpg",
  vinicius: "/cards/players/vinicius.jpg",
  raphinha: "/cards/players/raphinha.jpg",
  marquinhos: "/cards/players/marquinhos.jpg",
  alisson: "/cards/players/alisson.jpg",
  van_dijk: "/cards/players/van_dijk.jpg",
  frenkie_de_jong: "/cards/players/frenkie_de_jong.jpg",
  gakpo: "/cards/players/gakpo.jpg",
  courtois: "/cards/players/courtois.jpg",
  de_bruyne: "/cards/players/de_bruyne.jpg",
  doku: "/cards/players/doku.jpg",
  wirtz: "/cards/players/wirtz.jpg",
  musiala: "/cards/players/musiala.jpg",
  rudiger: "/cards/players/rudiger.jpg",
  donnarumma: "/cards/players/donnarumma.jpg",
  barella: "/cards/players/barella.jpg",
  bastoni: "/cards/players/bastoni.jpg",
  gvardiol: "/cards/players/gvardiol.jpg",
  modric: "/cards/players/modric.jpg",
  hakimi: "/cards/players/hakimi.jpg",
  bounou: "/cards/players/bounou.jpg",
  luis_diaz: "/cards/players/luis_diaz.jpg",
  davinson_sanchez: "/cards/players/davinson_sanchez.jpg",
  mane: "/cards/players/mane.jpg",
  koulibaly: "/cards/players/koulibaly.jpg",
  santiago_gimenez: "/cards/players/santiago_gimenez.png",
  edson_alvarez: "/cards/players/edson_alvarez.png",
  luis_malagon: "/cards/players/luis_malagon.png",
  pulisic: "/cards/players/pulisic.jpg",
  antonee_robinson: "/cards/players/antonee_robinson.jpg",
  mckennie: "/cards/players/mckennie.jpg",
} as const;

export function getCardPortraitSrc(portraitKey: string): string | null {
  return CARD_PORTRAIT_SOURCES[portraitKey as keyof typeof CARD_PORTRAIT_SOURCES] ?? null;
}
